### PR TITLE
Fix color of "COMMANDER 16" on splashscreen.

### PR DESCRIPTION
**Pull request by hanneseder-net**
Hi Jimmy,

My son and me love your game, thanks for sharing! Here is a small fix, since I got curious about working with x16emu.

Best,
-Hannes

### CODE REVIEW

**Comment by JimmyDansbo** [comment]
Thank you for your interest and time you have put into fixing my spaghetti-code :) I actually thought that I had fixed the color and placement of the logo... Maybe I forgot to push the changes. Regarding the border, It was actually my intention to leave it as is when user pressed a key for next level, but black is just as good.
As for the LVLtoPET function, I would love to merge it, but could you please add comments that explain how it works? I know that the one I wrote is long and convoluted, but one of my main goals of the game is to give as much explanation of the code as possible in order to help new-comers along. (not sure if I have succeded, but that was the thought).

**Comment by hanneseder-net** [comment]
Hi Jimmy,

Thanks for coming back to me. My intention at this point was only to ask
for the color on splashscreen to get merged, yeah maybe the placement too.

With the rest I was just toying around a bit. I don't have a strong opinion
on the border color for the next level. Time permitting I can spend some
time commenting on the LVLtoPET function, although I need to reverse
engineer myself how this actually works. I thought I added a link to the
origin of this code to the commit message, but apparently not. :)

Thanks again for writing and sharing this game, I had a very strong
childhood flashback with playing and hacking on it. :)

Best,
-Hannes

**Review by JimmyDansbo — APPROVED** [review]
Nice catches, thanks for your help :)

**Comment by hanneseder-net** [comment]
How do you want to proceed? Should I move the changes you want to pull to a
different branch and resent a pull request?

**Comment by JimmyDansbo** [comment]
I think that would be best. I would like to ensure that you are credited for the corrections, but I would also like to hold off on the LVLtoPET update until we have some comments explaining the code.

**Comment by hanneseder-net** [comment]
I have sent you a new pull request with just the fixes for the splashscreen.

**Pull request closed without merging**
